# Dockerfile for node client

# Build react client
FROM node:18-alpine

# Working directory be app
WORKDIR /usr/app

COPY package.json ./

###  Installing dependencies

RUN npm install --silent

# copy local files to app folder
COPY . /usr/app/code


EXPOSE 5000

# CMD ["npm","start"]